### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gpustat'

### ISSUE THREAD

**Issue by Chu4nQ1n** [eureka-research/DrEureka#11]
(dr_eureka) chuan@chuan-ubuntu:~/Downloads/Github Projetcs/DrEureka/eureka$ python eureka.py env=forward_locomotion
[2024-06-26 19:32:44,510][root][INFO] - Workspace: /home/chuan/Downloads/Github Projetcs/DrEureka/eureka/outputs/eureka/2024-06-26_19-32-44
[2024-06-26 19:32:44,510][root][INFO] - Project Root: /home/chuan/Downloads/Github Projetcs/DrEureka/eureka
[2024-06-26 19:32:44,510][root][INFO] - Using LLM: gpt-4-0125-preview
[2024-06-26 19:32:44,510][root][INFO] - Task: Forward Locomotion
[2024-06-26 19:32:44,510][root][INFO] - Task description: To make the go1 quadruped run forward with a velocity of exactly 2.0 m/s in the positive x direction of the global coordinate frame. The policy will be trained in simulation and deployed in the real world, so the policy should be as steady and stable as possible with minimal action rate. Specifically, as it's running, the torso should remain near a z position of 0.34, and the orientation should be perpendicular to gravity. Also, the legs should move smoothly and avoid the DOF limits.
[2024-06-26 19:32:44,510][root][INFO] - Iteration 0: Generating 16 samples with gpt-4-0125-preview
[2024-06-26 19:34:49,752][root][INFO] - Iteration 0: Prompt Tokens: 1869, Completion Tokens: 9491, Total Tokens: 16967
[2024-06-26 19:34:49,753][root][INFO] - Iteration 0: Processing Code Run 0
Error executing job with overrides: ['env=forward_locomotion']
Traceback (most recent call last):
  File "eureka.py", line 160, in main
    set_freest_gpu()
  File "/home/chuan/Downloads/Github Projetcs/DrEureka/eureka/utils/misc.py", line 9, in set_freest_gpu
    freest_gpu = get_freest_gpu()
  File "/home/chuan/Downloads/Github Projetcs/DrEureka/eureka/utils/misc.py", line 14, in get_freest_gpu
    sp = subprocess.Popen(['gpustat', '--json'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/chuan/anaconda3/envs/dr_eureka/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/chuan/anaconda3/envs/dr_eureka/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gpustat'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Chu4nQ1n** [comment]
Anyone knows how to solve this problem? Thx

**Comment by aeites** [comment]
I solved this with `pip install gpustat`.
